name: AEIOU-master-x64-Release-Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Set datetime
      run: |
        $datetime = Get-Date -Format "yyyyMMdd-HHmm"
        echo "datetime=$datetime" | Out-File -Encoding utf8 .env # .envファイルを新規作成し、環境変数を書き込む

    - name: Use datetime
      shell: powershell
      run: |
        Get-Content .env | ForEach-Object {
          $_.Split("=") | ForEach-Object { $key = $_[0]; $value = $_[1]; Set-Variable -Name $key -Value $value } # .envファイルを読み込み、環境変数を設定
        }
        Write-Host $datetime # datetime環境変数を出力

    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore AEIOU/AEIOU.sln # パスを修正

    - name: Create temporary directory
      run: mkdir temp-build

    - name: Build solution in temporary directory
      run: msbuild AEIOU/AEIOU.sln /p:Configuration=Release /p:Platform=x64 /p:OutDir=D:\a\temp-build # 出力先ディレクトリを絶対パスで指定

    - name: Create Output Directory
      run: mkdir release-build

    - name: Zip Executable
      run: |
        $datetime = Get-Date -Format "yyyyMMdd-HHmm"
        7z a release-build\AEIOU-$datetime.zip D:\a\temp-build\AEIOU.exe  # パスを修正

    - name: Upload Artifact
      uses: actions/upload-artifact@v4 # v3 から v4 に変更
      with:
        name: AEIOU-x64-Release-${{ env.datetime }} # $datetime を ${{ env.datetime }} に変更
        path: release-build

    - name: Clean up temporary directory
      run: Remove-Item -Recurse -Force temp-build # rm -rf temp-build を Remove-Item に変更
